repos:
    - repo: local
      hooks:
          - id: nox
            name: nox
            entry: nox
            language: system
            types: [python]
            pass_filenames: false
            verbose: true
            always_run: true
